discount: ${discount}
target_entropy: -6.0
policy_lr: 3e-4
qf_lr: 3e-4
alpha_prime_lr: 1e-4
optimizer_type: adam
soft_target_update_rate: 5e-3
cql_n_actions: 4
cql_lagrange: false
cql_target_action_gap: 5.0
alpha_prime: 5.0
target_update_interval: 1
max_grad_norm: 1.0
cql_temp: 1.0

bc_start_step: 2000  # Will be overwritten by bc_start_epochs * steps_per_epoch
bc_transition_steps: 1000  # Will be overwritten by bc_transition_epochs * steps_per_epoch
bc_regularization_weight: 0.3  # Keep BC regularization after transition to prevent policy collapse