discount: ${discount}
alpha_multiplier: 1.0
backup_entropy: true
target_entropy: -6.0
policy_lr: 1e-4
qf_lr: 3e-4
fixed_alpha: 0.1
alpha_prime_lr: 3e-5
optimizer_type: adam
soft_target_update_rate: 5e-3
cql_n_actions: 10
cql_lagrange: true
cql_target_action_gap: 5.0
alpha_prime: 1.0
target_update_interval: 1
max_grad_norm: 1.0
cql_temp: 1.0

bc_start_step: 5000