defaults:
- env: env
device: cuda:0
ckpt_path: ./checkpoints/act_policy.pth
statistics_path: ./dataset/statistics.yaml
observation_dim: 6
action_dim: 6
hidden_dim: 512
latent_dim: 32
num_encoder_layers: 4
num_decoder_layers: 4
num_heads: 8
chunk_size: 30
rollout_size: 5
dim_feedforward: 2048
backbone_name: resnet18
image_resize: 256
image_size: 224
proprio_norm_type: max_min
action_norm_type: max_min
temporal_ensemble: true
temporal_decay: 0.01
num_episodes: 10
max_steps: 300
freq: 10
save_data: false
save_path: ./rollout_act
episode_idx: 0
