defaults:
- env: env
device: cuda:0
ckpt_path: ./checkpoints/bc_policy.pth
statistics_path: ./dataset/statistics.yaml
observation_dim: 6
action_dim: 6
hidden_dim: 256
policy_obs_proj_arch: 256-256-256-256
policy_out_proj_arch: 256-256-256-256
policy_log_std_multiplier: 1.0
policy_log_std_offset: -1.0
orthogonal_init: true
image_resize: 256
image_size: 224
proprio_norm_type: max_min
action_norm_type: max_min
num_episodes: 10
max_steps: 1000
freq: 30
save_data: true
save_path: ./rollout_bc_intervention
episode_idx: 0
