defaults:
- iql: iql_defaults
- logging: logging_defaults
- dataset: dataset_defaults
observation_dim: 6
action_dim: 6
seed: 42
save_model: false
batch_size: 32
num_workers: 4
preload_to_memory: true
hidden_dim: 256
orthogonal_init: true
policy_obs_proj_arch: 256-256-256-256
policy_out_proj_arch: 256-256-256-256
policy_log_std_multiplier: 1.0
policy_log_std_offset: -1.0
train_policy_backbone: true
q_obs_proj_arch: 256-256
q_out_proj_arch: 256-256
train_q_backbone: true
v_obs_proj_arch: 256-256
v_out_proj_arch: 256-256
train_v_backbone: true
train_iql_epochs: 1000
use_lr_scheduler: true
warmup_ratio: 0.05
min_lr_ratio: 0.1
torch_compile_mode: disable
save_every_n_epoch: 100
ckpt_path: ./checkpoints
load_ckpt_path: ''
device: cuda:0
discount: 0.99
