env_name: "ur_env_v0"
ip: "172.16.11.233"
ft_sensor_topic: "/ft_filtered"
camera_topic: "/camera/color/image_raw/compressed"

image_size: 256

M: [5.0, 5.0, 5.0, 0.05, 0.05, 0.05]
D: [300.0, 300.0, 300.0, 8.0, 8.0, 8.0]
K: [4000.0, 4000.0, 4000.0, 80.0, 80.0, 80.0]
threshold_low: [10.0, 0.6]
threshold_high: [12.0, 0.8]

ctrl_freq: 100.0
action_freq: 100.0

max_env_steps: 10000

reset_pose: [0.5065703568410502, 0.1680701835871387, -0.11434557686026554, -1.7270236895623132, -0.7062649157836881, 0.5207196925055085]

random_lower: [-0.05, -0.05, -0.02, -0.1, -0.1, -0.1]
random_upper: [0.05, 0.05, 0.05, 0.1, 0.1, 0.1]

