env_name: "ur_env_v0"
ip: "172.16.11.233"
ft_sensor_topic: "/ft_filtered"
camera_topic: "/camera/color/image_raw"
spacemouse_twist_topic: "spacemouse/twist"
spacemouse_buttons_topic: "spacemouse/buttons"
base_to_world_file: "/home/cyx/project/cal-ql-torch/assets/left_base_to_world.npy"
image_size: 256

M: [3.0, 3.0, 3.0, 0.15, 0.15, 0.15]
D: [3.0, 3.0, 3.0, 0.1, 0.1, 0.1]
K: [2000.0, 2000.0, 2000.0, 200.0, 200.0, 200.0]
threshold_low: [8.0, 0.1]
threshold_high: [10.0, 0.2]

ctrl_freq: 100.0

max_env_steps: 10000

reset_pose: [ 1.04559550e-04, 4.77023892e-01, 5.03386064e-01, -1.91925559e+00, -1.92356314e+00, 4.80659572e-01]

# random_lower: [-0.05, -0.05, -0.02, -0.1, -0.1, -0.1]
# random_upper: [0.05, 0.05, 0.05, 0.1, 0.1, 0.1]

teleop_twist_scale: [0.05, 0.05, 0.05, 0.1, 0.0, 0.0]

