env_name: "ur_env_v0"
ip: "172.16.11.233"
ft_sensor_topic: "/ft_filtered"
camera_topic: "/camera/color/image_raw"
spacemouse_twist_topic: "spacemouse/twist"
spacemouse_buttons_topic: "spacemouse/buttons"
base_to_world_file: "/home/cyx/project/cal-ql-torch/assets/left_base_to_world.npy"
image_size: 256

M: [50.0, 50.0, 50.0, 1.0, 1.0, 1.0]
D: [5000.0, 5000.0, 5000.0, 100.0, 100.0, 100.0]
# M: [15.0, 15.0, 15.0, 0.3, 0.3, 0.3]
# D: [80.0, 80.0, 80.0, 0.8, 0.8, 0.8]
# K: [2000.0, 2000.0, 2000.0, 200.0, 200.0, 200.0]
threshold_low: [2.0, 0.1]
threshold_high: [3.0, 0.2]
# threshold_low: [200.0, 0.1]
# threshold_high: [300.0, 0.2]
ctrl_freq: 100.0

max_env_steps: 10000

reset_pose: [-0.22140258,  0.60002238,  0.34146388,  1.75996952,  1.76004894,  0.72913837]

random_lower: [-0.005, -0.01, -0.01, -0.2, -0.0, -0.0]
random_upper: [0.005, 0.01, 0.01, 0.2, 0.0, 0.0]

teleop_twist_scale: [0.05, 0.05, 0.05, 0.0, 0.1, 0.0]

