defaults:
  - logging: logging_defaults
  - dataset: dataset_defaults

observation_dim: 6
action_dim: 6


seed: 42
batch_size: 256
num_workers: 16

# Data sampling settings for studying data efficiency
# sample_ratio: ratio of data to use (0.0, 1.0], default 1.0 uses all data
# sample_seed: fixed seed for sampling to ensure consistency across multi-GPU training
sample_ratio: 1.0
sample_seed: 42


# Architecture & policy hyperparameters
hidden_dim: 256
orthogonal_init: true

policy_obs_proj_arch: '256-256-256-256'
policy_out_proj_arch: '256-256-256-256'
policy_log_std_multiplier: 1.0
policy_log_std_offset: -1.0
train_policy_backbone: true


learning_rate: 3e-4
train_bc_epochs: 100

torch_compile_mode: "max-autotune"

save_every_n_epoch: 20
eval_every_n_epochs: 10
ckpt_path: ./checkpoints
load_ckpt_path: ""

device: cuda:0
discount: 0.99