defaults:
  - td3bc: td3bc_defaults
  - logging: logging_defaults
  - dataset: dataset_defaults

observation_dim: 18
action_dim: 7

seed: 42
batch_size: 256
num_workers: 4

# Architecture & policy hyperparameters
hidden_dim: 256
orthogonal_init: false

policy_obs_proj_arch: '256-256-256-256'
policy_out_proj_arch: '256-256-256-256'
train_policy_backbone: false

q_obs_proj_arch: '256-256-256-256'
q_out_proj_arch: '256-256-256-256'
train_q_backbone: false

# Training schedule
train_epochs: 100

save_every_n_epoch: 20
ckpt_path: ./checkpoints
load_ckpt_path: ""

discount: 0.99
device: cuda:0
